- numpy 연산
  - 연산자를 이용할 경우에는 +,-,*,/
  - 함수를 사용할 경우에는 add(), subtract(), multiply(), divide()
  - 배열 a와 배열 b가 있을 때, a + b는 a[0]+b[0], a[1]+b[1], ...와 같은 방식으로 결과를 리턴

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [14]:
# c = a + b
c = np.add(a,b)
c

array([5, 7, 9])

In [15]:
# c = a - b
c = np.subtract(a,b)
c

array([-3, -3, -3])

In [16]:
# c = a * b
c = np.multiply(a,b)
c

array([ 4, 10, 18])

In [17]:
# c = a / b
c = np.divide(a,b)
c

array([0.25, 0.4 , 0.5 ])

In [18]:
list1 = [
    [1,2]
   ,[3,4]
]

list2 = [
    [5,6]
   ,[7,8]
]

a = np.array(list1)
b = np.array(list2)

- numpy에서 vector와 matrix의 product를 구하기 위해서 dot()함수를 이용한다.

In [20]:
product = np.dot(a,b)
product
# 1*5+2*7=19, 1*6+2*6=22
# 3*5+4*7=43, 3*6+4*8=50

array([[19, 22],
       [43, 50]])

- numpy에서는 배열간의 연산을 위한 여러 함수들을 제공하는데,
- 각배열의 요소를 더하는 함수 sum(), 배열의 요소들을 곱하는 prod()함수
- 이 함수들은 axis 옵션을 사용한다. axis 0이면 칼럼끼리 더함, 1이면 행끼리 더함

In [22]:
d = np.array([[1,2],[3,4]])
s = np.sum(d)
s

10

In [23]:
s = np.sum(d, axis = 0)
s

array([4, 6])

In [24]:
s = np.sum(d, axis = 1)
s

array([3, 7])

In [25]:
p = np.prod(d)
p

24

In [26]:
p = np.prod(d, axis = 0)
p

array([3, 8])

In [27]:
p = np.prod(d, axis = 1)
p

array([ 2, 12])