## Numpy/Pandas 소개

＊Numpy는 과학 계산을 위한 라이브러리로 다차원 배열을 처리하는데
  필요한 여러 기능을 제공한다.
 pip3 install numpy
 
 - numpy 배열
  numpy에서 배열은 동일한 타입의 값들을 갖는다
  배열의 차원을 rank라고 한다.
 
  shape : 각 차원의 크기를 튜플로 표시한 것
   예> 2행,3열 인 2차원 배열은 rank는 2이고, shape(2,3)
  
  numpy배열을 생성
  - 파이썬의 리스트를 사용하는 방법
    - array() 함수의 인자로 리스트를 넣어 생성한다.
    - numpy.array([1,2,3])
  - numpy에서 제공하는 함수를 사용하는 방법
    - zeros()함수는 배열에 모두 0을 집어넣고
    - ones()함수는 모두 1을 집어넣는다..
    - full()함수는 사용자가 지정한 값을 넣는데 사용
    - eye()함수는 대각선으로는 1이고 나머지는 0
    
    - range(n) : 0 ~ n-1 까지의 숫자를 생성하는 함수
    - reshape() : 다차원으로 변형하는 함수

In [2]:
import numpy as np

In [5]:
list1 = [1,2,3,4]
a = np.array(list1)
print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
b[0,0]

1

In [12]:
aa = np.zeros((2,2))
aa

array([[0., 0.],
       [0., 0.]])

In [13]:
type(aa)

numpy.ndarray

In [14]:
aa = np.ones((2,3))
aa

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
aa = np.full((2,3),10)
aa

array([[10, 10, 10],
       [10, 10, 10]])

In [17]:
aa = np.eye(4)
aa

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
aa = np.array(range(20)).reshape((5,4))
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])