#### numpy 브로드캐스트

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = 10

c = a * b
c

array([[10, 20],
       [30, 40]])

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([10,20])

z = x * y
z

array([[10, 40],
       [30, 80]])

In [4]:
x = np.array([[11,21], [34,43], [0,9]])
x

array([[11, 21],
       [34, 43],
       [ 0,  9]])

In [5]:
x[0][1]

21

In [8]:
for row in x:
    print(row)

[11 21]
[34 43]
[0 9]


#### 2차원 배열을 1차원 배열로 변환(평탄화) : flatten()

In [10]:
x = x.flatten()
x

array([11, 21, 34, 43,  0,  9])

In [11]:
x[np.array([1,3,5])]

array([21, 43,  9])

In [12]:
x[x > 25]

array([34, 43])

In [13]:
x > 25 # numpy 배열에 부등호 연산자를 사용한 결과는 bool 배열이다.

array([False, False,  True,  True, False, False])