- numpy 자료형(data Type)
  - int, float, bool(True/False), complex
  - 정수형(int:integer)
    - int8(-127~127), int16(-32768~32767), int32, int64 (부호가 있는 정수형)
    - uint(unsigned integer): uint8(0~255), uint16(0~65535), uint32, uint64
  - 실수형(float)
    - float16, float32, float64
  - complex
    - complex64  : 두 개의 32비트 부동소수점으로 표시되는 복소수
    - complex128 : 두 개의 64비트 부동소수점으로 표시된느 복소수
- 데이터의 type을 알아보기 위한 dtype 속성


In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)
x

1.0

In [4]:
type(x)

numpy.float32

In [5]:
x.dtype

dtype('float32')

In [9]:
z = np.arange(5, dtype = 'f')
z

array([0., 1., 2., 3., 4.], dtype=float32)

In [12]:
aa = np.array([1,2,3],dtype = 'f')
aa

array([1., 2., 3.], dtype=float32)

In [13]:
xx = np.int8(aa)
xx

array([1, 2, 3], dtype=int8)

In [18]:
bb = np.arange(10)
bb

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
cc = np.arange(3, 10, dtype = np.float)
cc

array([3., 4., 5., 6., 7., 8., 9.])

In [32]:
dd = np.arange(2, 3, 0.1)
dd

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])