 ### numpy 슬라이싱, 인덱싱, 연산
- numpy 슬라이싱

In [1]:
import numpy as np

In [2]:
list = [
        [1,2,3],
        [4,5,6],
        [7,8,9]
       ]
arr = np.array(list)

In [4]:
a = arr[0:2,0:2]
a

array([[1, 2],
       [4, 5]])

In [5]:
b = arr[1:,1:]
b

array([[5, 6],
       [8, 9]])

- numpy 정수 인덱싱(integer indexing)
  - numpy 배열 a에 대해서 a[[row1,row2],[col1,col2]는
    a[row1,col1]과 a[row2,col2]라는 두 개의 배열 요소 집합의미

In [9]:
list2 = [
         [1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]
        ]
arr2 = np.array(list2)

In [11]:
res = arr2[[0,2],[1,3]] # a[0,1], a[2,3]
res

array([ 2, 12])

- 부울린 인덱싱(boolean indexing)

In [12]:
list3 = [
         [1,2,3],
         [4,5,6],
         [7,8,9]
        ]
arr3 = np.array(list3)

In [13]:
b_arr = np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])

n = arr3[b_arr]
n

array([2, 4, 6, 8])

- 부울린 인덱싱 배열을 생성할 때 표현식으로 이용하기
  - 배열 a에 대해서 짝수인 배열 요소만 True로 지정하겠다
  - b_arr2=(a%2==0)

In [19]:
b_arr2 = (arr3 % 2 ==0)
b_arr2

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [20]:
arr3[b_arr2]

array([2, 4, 6, 8])

In [22]:
n2 = arr3[arr3 % 2 == 0]
n2

array([2, 4, 6, 8])