In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [3]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr[0]

array([0, 1, 2, 3])

In [5]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [5]:
df = DataFrame(np.arange(12).reshape(4,3),
               columns = list('bde'),
               index = ['Seosul', 'Kwangju', 'Daegu', 'Incheon'])
df

b   d   e
Seosul   0   1   2
Kwangju  3   4   5
Daegu    6   7   8
Incheon  9  10  11

In [6]:
s1 = df.ix[0]
s1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


b    0
d    1
e    2
Name: Seosul, dtype: int32

In [7]:
df - s1

b  d  e
Seosul   0  0  0
Kwangju  3  3  3
Daegu    6  6  6
Incheon  9  9  9

In [8]:
s2 = Series(range(3), index = list('bef'))
s2

b    0
e    1
f    2
dtype: int64

In [9]:
df + s2

b   d     e   f
Seosul   0.0 NaN   3.0 NaN
Kwangju  3.0 NaN   6.0 NaN
Daegu    6.0 NaN   9.0 NaN
Incheon  9.0 NaN  12.0 NaN

In [10]:
s3 = df['d']
s3

Seosul      1
Kwangju     4
Daegu       7
Incheon    10
Name: d, dtype: int32

In [11]:
df + s3

Daegu  Incheon  Kwangju  Seosul   b   d   e
Seosul     NaN      NaN      NaN     NaN NaN NaN NaN
Kwangju    NaN      NaN      NaN     NaN NaN NaN NaN
Daegu      NaN      NaN      NaN     NaN NaN NaN NaN
Incheon    NaN      NaN      NaN     NaN NaN NaN NaN

- 행에 대한 연산을 수행할 경우에는 함수를 이용한다.

In [12]:
df.add(s3, axis = 0)

b   d   e
Seosul    1   2   3
Kwangju   7   8   9
Daegu    13  14  15
Incheon  19  20  21

In [13]:
df.sub(s3, axis = 0)

b  d  e
Seosul  -1  0  1
Kwangju -1  0  1
Daegu   -1  0  1
Incheon -1  0  1