- scipy.sparse 주요 모률
- sparse matrix(희소 행렬)

- numpy에서 특수행렬을 만드는 함수
  - eye(N, M=,k=,dtype=) 함수는 항등행렬을 생성하는 함수
  - N=행의수, M=열의수, k=대각의 위치
- diag()함수는 정방행렬에서 대각 요소만 추출하여 백터를 만드는 함수
  - diag(v, k=)
  - diag()함수는 반대로 벡터요소를 대각요소로 하는 정방행렬을 만들기도 한다.

In [1]:
import numpy as np

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
np.eye(4,k = 1, dtype = int)

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [23]:
np.eye(4,M =5, k = 1, dtype = int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [24]:
x = np.eye(5, dtype = int)
np.diag(x)

array([1, 1, 1, 1, 1])

In [29]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.diag(x)

array([0, 4, 8])

In [28]:
np.diag(x, k = 1)

array([1, 5])

In [27]:
np.diag(x, k = -1)

array([3, 7])

In [31]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])