- scipy에서 scikit-learn 알고리즘을 구현 할 때 가장 중요한 기능 scipy.sparse 모듈이다
- 이때 희소 행렬 기능은 주요 기능 중의 하나이다.
- 희소 행렬(sparse matrix)

In [1]:
import numpy as np
from scipy import sparse

In [3]:
b1 = np.eye(4, dtype = int)
b1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

- sparse.csr_matrix() 메소드 : 0이 아닌 원소만 저장
- CSR(Compressed Sparse Row), CRS - 행의 인덱스를 압축해서 저장

In [8]:
sparse_matrix = sparse.csr_matrix(b1)
print("Scipy의 CSR 행렬 : \n{}".format(sparse_matrix))

Scipy의 CSR 행렬 : 
  (0, 0)	1
  (1, 1)	1
  (2, 2)	1
  (3, 3)	1


In [9]:
b2 = np.eye(5, k = -1, dtype = int)
b2

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [10]:
sparse_matrix = sparse.csr_matrix(b2)
print("Scipy의 CSR 행렬 : \n{}".format(sparse_matrix))

Scipy의 CSR 행렬 : 
  (1, 0)	1
  (2, 1)	1
  (3, 2)	1
  (4, 3)	1


In [11]:
b3 = np.arange(16).reshape(4,4)
b3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
x = np.diag(b3)
x

array([ 0,  5, 10, 15])

In [14]:
y = np.diag(np.diag(b3))
y

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [15]:
sparse_matrix = sparse.csr_matrix(y)
print("Scipy의 CSR 행렬 : \n{}".format(sparse_matrix))

Scipy의 CSR 행렬 : 
  (1, 1)	5
  (2, 2)	10
  (3, 3)	15


- 희소행렬을 직접 만들 때 사용하는 포맷
- COO 포맷(Coordinate 포맷)

In [16]:
data = np.ones(4)
data

array([1., 1., 1., 1.])

In [20]:
row_indices = np.arange(4)
col_indices = np.arange(4)

eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO 표현 : \n{}".format(eye_coo))

COO 표현 : 
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
